name: zebra_printer
description: Flutter management package for Zebra printers. Uses Zebra Link-OS SDK for Bluetooth & Network discovery, ZPL printing, and printer management.
version: 0.2.3
homepage: https://github.com/Sameetdmr/zebra_printer
repository: https://github.com/Sameetdmr/zebra_printer
issue_tracker: https://github.com/Sameetdmr/zebra_printer/issues
documentation: https://github.com/Sameetdmr/zebra_printer/blob/main/README.md

environment:
  sdk: ^3.7.2
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sameetdmr.zebra_printer
        pluginClass: ZebraPrinterPlugin

topics:
  - zebra
  - printer
  - bluetooth
  - zpl
  - label-printing